### ISSUE TITLE
Failed to build from docker 

### ISSUE THREAD

**Issue by alisoviejo** [mlperf/mobile_app#65]
On Ubuntu 16.04, tried to build from the docker. 
docker run \
    -v `pwd`:/mobile_app \
    -v <path to your cache dir>:/cache \
    -w /mobile_app \
    thaink/android-bazel:latest --output_user_root=/cache/bazel build \
    -c opt --cxxopt='--std=c++14' \
    --fat_apk_cpu=x86,arm64-v8a,armeabi-v7a \
    //java/org/mlperf/inference:mlperf_app

Got the following error. 
------------------------------

platform_sw@MSL-Platform-SW:~/val2017/mobile_app-master_git/mobile_app$ bazel build -c opt --cxxopt='--std=c++14' \
>     --fat_apk_cpu=x86,arm64-v8a,armeabi-v7a \
>     //java/org/mlperf/inference:mlperf_app
Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'org_mlperf_inference' which is a new_git_repository (rule definition at /home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git.bzl:182:22):
 - /home/platform_sw/val2017/mobile_app-master_git/mobile_app/WORKSPACE:103:1
 - /home/platform_sw/val2017/mobile_app-master_git/mobile_app/WORKSPACE:103:1
ERROR: An error occurred during the fetch of repository 'org_mlperf_inference':
   Traceback (most recent call last):
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git.bzl", line 170
		_clone_or_update(ctx)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
		fetch(ctx, git_repo)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 129, in fetch
		_git_maybe_shallow(ctx, <5 more arguments>)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 171, in _git_maybe_shallow
		_error(ctx.name, <2 more arguments>)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(<1 more arguments>)
error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @org_mlperf_inference:
Timed out
ERROR: /home/platform_sw/val2017/mobile_app-master_git/mobile_app/cpp/BUILD:30:1: //cpp:mlperf_driver depends on @org_mlperf_inference//:loadgen in repository @org_mlperf_inference which failed to fetch. no such package '@org_mlperf_inference//': Traceback (most recent call last):
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git.bzl", line 170
		_clone_or_update(ctx)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
		fetch(ctx, git_repo)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 129, in fetch
		_git_maybe_shallow(ctx, <5 more arguments>)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 171, in _git_maybe_shallow
		_error(ctx.name, <2 more arguments>)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(<1 more arguments>)
error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @org_mlperf_inference:
Timed out
ERROR: Analysis of target '//java/org/mlperf/inference:mlperf_app' failed; build aborted: no such package '@org_mlperf_inference//': Traceback (most recent call last):
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git.bzl", line 170
		_clone_or_update(ctx)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
		fetch(ctx, git_repo)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 129, in fetch
		_git_maybe_shallow(ctx, <5 more arguments>)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 171, in _git_maybe_shallow
		_error(ctx.name, <2 more arguments>)
	File "/home/platform_sw/.cache/bazel/_bazel_platform_sw/cb17f3c56d13dc85dccc593cfa55d0b1/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(<1 more arguments>)
error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @org_mlperf_inference:
Timed out
INFO: Elapsed time: 607.805s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (128 packages loaded, 8589 targets configured)

**Comment by thaink** [comment]
Hi alisoviejo,
The issue will be fixed with https://github.com/mlperf/mobile_app/pull/67
