### ISSUE TITLE
Crash after initial app startup

### ISSUE THREAD

**Issue by Michael137** [mlperf/mobile_app#69]
I have consistently been experiencing crashes when performing the following:
1. Open app and let models download
2. Run evaluation

In the adb logcat I get following crash dump:
```

03-31 16:08:29.054  5202  5202 I MLPerfEvaluation: logProgress: Ready. Click the Run button to evaluate.
03-31 16:08:29.054  5202  5202 D MLPerfEvaluation: All missing files are extracted.
03-31 16:08:29.054  5202  5202 I MLPerfEvaluation: logProgress: All missing files are extracted.
03-31 16:08:29.054  5202  5202 I MLPerfEvaluation: logProgress: Ready. Click the Run button to evaluate.
<---- Snipped ----->
03-31 16:08:32.654  5202  5202 D AndroidRuntime: Shutting down VM
03-31 16:08:32.655  5202  5202 E AndroidRuntime: FATAL EXCEPTION: main
03-31 16:08:32.655  5202  5202 E AndroidRuntime: Process: org.mlperf.inference, PID: 5202
03-31 16:08:32.655  5202  5202 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.Set.iterator()' on a null object reference
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at org.mlperf.inference.MLPerfEvaluation.playButtonListen
er(MLPerfEvaluation.java:239)
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at org.mlperf.inference.MLPerfEvaluation.bridge$lambda$0$
MLPerfEvaluation(Unknown Source:0)
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at org.mlperf.inference.MLPerfEvaluation$$Lambda$0.onClic
k(Unknown Source:2)
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at android.view.View.performClick(View.java:6597)
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at android.view.View.performClickInternal(View.java:6574)
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at android.view.View.access$3100(View.java:778)
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at android.view.View$PerformClick.run(View.java:25885)
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:873)
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:99)
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:193)
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:67
18)
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCalle
r.run(RuntimeInit.java:493)
03-31 16:08:32.655  5202  5202 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.jav
a:858)

```

Looks like it happens in MLPerfEvaluation.java:239 because **delegates** is null. On subsequent starts of the application, running the evaluation doesn't crash.

**Comment by thaink** [comment]
Hi Michael,
If you already installed the app before, could you try again by uninstall it and install the newer version?
In previous version, the preference for delegates is stored as string. So you need to uninstall the app to clear that preference first.

**Comment by Michael137** [comment]
I'm building the version in the master branch. I have been doing:
```
adb uninstall "org.mlperf.inference"
adb install bazel-bin/java/org/mlperf/inference/mlperf_app.apk
```

**Comment by thaink** [comment]
Hi Michael,
I cannot reproduct this issue. could you try the latest master or a fix I propose in the branch https://github.com/mlperf/mobile_app/tree/test1_startup_crash?

**Comment by Michael137** [comment]
Thanks for looking into it. It's still crashing on both branches but it might be an issue with the manually built Android version that I'm running. I'll close this issue for now and reopen if the behaviour remains on stock Android.

**Comment by thaink** [comment]
Thanks, may be that version has difference behavior of Preference.getStringSet.
